apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-service
  namespace: fxtravel
  labels: { app: train-service }
spec:
  replicas: 1
  selector: { matchLabels: { app: train-service } }
  template:
    metadata: { labels: { app: train-service } }
    spec:
      containers:
        - name: train-service
          image: ehernng/train-service:1.0.1
          ports:
            - containerPort: 8080
          env:
            - { name: DEGRADE_ALL, value: "false" }
            - { name: SPRING_CONFIG_IMPORT, value: "" }
            - { name: SPRING_DATASOURCE_URL, value: "jdbc:h2:mem:traindb;DB_CLOSE_DELAY=-1;MODE=MySQL" }
            - { name: SPRING_DATASOURCE_DRIVER_CLASS_NAME, value: "org.h2.Driver" }
            - { name: SPRING_DATASOURCE_USERNAME, value: "sa" }
            - { name: SPRING_DATASOURCE_PASSWORD, value: "" }
            - { name: SPRING_JPA_HIBERNATE_DDL_AUTO, value: "update" }
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "1", memory: "512Mi" }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8080 }
            initialDelaySeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8080 }
            initialDelaySeconds: 20
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: train-service-hpa
  namespace: fxtravel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: train-service
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15

