server:
  port: 8060

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://m-config-svc:8901
  cloud:
    # config客户端配置
    config:
      # 分支名称
      label: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://m-eureka-svc:8761/eureka
